"""DiscussionRoleExtractor — extract discussion roles from natural language.

Pure domain service — no I/O, no external dependencies. Uses regex to detect
role specifications in goal text (English and Japanese).

Roles are free-form strings defined by the user or generated by LLM.
No hardcoded role types, enums, or presets — the framework provides
only the extraction mechanism.
"""

from __future__ import annotations

import re

# ── Explicit label patterns ──
# "role: X, Y, Z" / "roles: X, Y" / "役割: X, Y" / "役割はX、Y"
_ROLE_LABEL_RE = re.compile(
    r"(?:roles?|役割)\s*[:：は]\s*(.+?)(?:\s*[。.]|\s*$)",
    re.IGNORECASE,
)

# ── Japanese "として" pattern ──
# "賛成派として、反対派として" → ["賛成派", "反対派"]
_TOSHITE_RE = re.compile(
    r"([\w\u3040-\u9FFF]+)として",
)

# ── Japanese perspective pattern ──
# "消費者の立場で、生産者の立場で" / "の視点で" / "の観点で"
_PERSPECTIVE_RE = re.compile(
    r"([\w\u3040-\u9FFF]+)の(?:立場|視点|観点)で",
)

# ── English "as a [role]" pattern ──
# "Claude as a researcher, Gemini as a critic"
_AS_ROLE_RE = re.compile(
    r"\bas\s+(?:an?\s+)?([\w][\w\s]*?)(?:\s*[,、]|\s+and\s+|\s*$)",
    re.IGNORECASE,
)

# Role separator for label pattern
_SEPARATOR_RE = re.compile(r"\s*[,、]\s*|\s*と\s*")

# Model aliases to filter out from として matches
_MODEL_NAMES = frozenset(
    {
        "claude",
        "gpt",
        "gemini",
        "openai",
        "anthropic",
        "ollama",
        "chatgpt",
        "codex",
        "google",
    }
)

# Prompt template for LLM-based role generation
_ROLE_GENERATION_PROMPT = """\
You are assigning discussion roles for a multi-agent collaboration.

Task: {goal}
Number of participants: {count}

Generate exactly {count} distinct discussion roles. Each role should bring \
a unique perspective that helps achieve the task goal.

Return ONLY a JSON array of role description strings.
Example: ["quantitative data analyst", "industry domain expert"]

Rules:
- Roles must be relevant to the specific task
- Each role should provide a distinct viewpoint
- Role descriptions should be concise (2-6 words)
- No markdown, no explanation — ONLY the JSON array"""


class DiscussionRoleExtractor:
    """Extract discussion roles from goal text.

    Pure domain service — no I/O, fully deterministic.

    Examples::

        roles = DiscussionRoleExtractor.extract(
            "claudeとgeminiで議論して、role: 賛成派, 反対派"
        )
        assert roles == ["賛成派", "反対派"]

        roles = DiscussionRoleExtractor.extract("分析して")
        assert roles is None
    """

    @staticmethod
    def extract(goal: str) -> list[str] | None:
        """Extract role specifications from goal text.

        Returns list of role strings if found, None otherwise.
        Checks patterns in priority order:
        1. Explicit label (role:/roles:/役割:)
        2. Japanese として pattern
        3. Japanese の立場で/の視点で/の観点で pattern
        4. English "as a [role]" pattern
        """
        # 1. Explicit label
        match = _ROLE_LABEL_RE.search(goal)
        if match:
            raw = match.group(1).strip()
            roles = [r.strip() for r in _SEPARATOR_RE.split(raw) if r.strip()]
            if roles:
                return roles

        # 2. として pattern (filter out model names)
        toshite = _TOSHITE_RE.findall(goal)
        filtered = [m for m in toshite if m.lower() not in _MODEL_NAMES]
        if len(filtered) >= 2:
            return filtered

        # 3. の立場で / の視点で / の観点で pattern
        perspective = _PERSPECTIVE_RE.findall(goal)
        if len(perspective) >= 2:
            return perspective

        # 4. English "as a [role]" pattern
        as_roles = _AS_ROLE_RE.findall(goal)
        if len(as_roles) >= 2:
            return [r.strip() for r in as_roles if r.strip()]

        return None

    @staticmethod
    def build_role_generation_prompt(goal: str, count: int) -> str:
        """Build prompt for LLM to generate discussion roles dynamically.

        The LLM decides what roles make sense for the given task.
        Returns a system prompt string for the LLM call.
        """
        return _ROLE_GENERATION_PROMPT.format(goal=goal, count=count)
